### ISSUE TITLE
Sandbox

### ISSUE THREAD

**Issue by ikermart** [treslines/pagseguro_android#1]
Boa tarde Ricardo, parabéns pelo aplicativo.
Tentei adaptar o teu código apontando para SANDBOX, para o meu, então a ultima fase "Seu pagamento esta em fase de analise..." queda travado lá e não volta ao Activity pai (onActivityResult), tipo "A transação foi efetuada com sucesso...". Quando esta em "fase de analise" não retorna ? queda parado lá?
Obrigado!

**Comment by treslines** [comment]
Oi ikermart!

Ao concluir o processo, pressione back no aparelho e veja o retorno. 

abraço,
ricardo
